// Mock data for demo mode
import type {
  User,
  Transaction,
  DashboardData,
  UpcomingDeadline,
  Document,
} from '@/types';

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === 'true';

export const mockUser: User = {
  id: 'demo-user-1',
  email: 'demo@airportcoordinator.com',
  full_name: 'Sarah Mitchell',
  role: 'transaction_coordinator',
  organization_id: 'demo-org-1',
};

export const mockDashboard: DashboardData = {
  active_transactions: 12,
  pending_deadlines: 8,
  documents_needing_review: 3,
  completed_this_month: 5,
  total_volume: 4750000,
};

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    status: 'active',
    transaction_type: 'purchase',
    property_address: {
      street: '1425 Ocean Drive',
      city: 'Miami Beach',
      state: 'FL',
      zip_code: '33139',
    },
    purchase_price: 875000,
    closing_date: '2026-02-15',
    effective_date: '2026-01-10',
    parties: [
      { role: 'buyer', name: 'Michael Chen', email: 'mchen@email.com' },
      { role: 'seller', name: 'Patricia Williams', email: 'pwilliams@email.com' },
    ],
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-01-18T14:30:00Z',
    buyer_name: 'Michael Chen',
    seller_name: 'Patricia Williams',
  },
  {
    id: 'tx-2',
    status: 'pending_close',
    transaction_type: 'sale',
    property_address: {
      street: '892 Brickell Ave',
      unit: '2405',
      city: 'Miami',
      state: 'FL',
      zip_code: '33131',
    },
    purchase_price: 1250000,
    closing_date: '2026-01-25',
    effective_date: '2025-12-20',
    parties: [
      { role: 'buyer', name: 'David & Emily Rodriguez', email: 'rodriguez@email.com' },
      { role: 'seller', name: 'James Thompson', email: 'jthompson@email.com' },
    ],
    created_at: '2025-12-15T09:00:00Z',
    updated_at: '2026-01-17T11:00:00Z',
    buyer_name: 'David & Emily Rodriguez',
    seller_name: 'James Thompson',
  },
  {
    id: 'tx-3',
    status: 'active',
    transaction_type: 'purchase',
    property_address: {
      street: '3200 Collins Ave',
      unit: '1802',
      city: 'Miami Beach',
      state: 'FL',
      zip_code: '33140',
    },
    purchase_price: 625000,
    closing_date: '2026-03-01',
    effective_date: '2026-01-15',
    parties: [
      { role: 'buyer', name: 'Jennifer Martinez', email: 'jmartinez@email.com' },
      { role: 'seller', name: 'Robert & Lisa Kim', email: 'kim@email.com' },
    ],
    created_at: '2026-01-12T08:00:00Z',
    updated_at: '2026-01-18T16:45:00Z',
    buyer_name: 'Jennifer Martinez',
    seller_name: 'Robert & Lisa Kim',
  },
  {
    id: 'tx-4',
    status: 'active',
    transaction_type: 'dual',
    property_address: {
      street: '4521 Ponce de Leon Blvd',
      city: 'Coral Gables',
      state: 'FL',
      zip_code: '33146',
    },
    purchase_price: 1875000,
    closing_date: '2026-02-28',
    effective_date: '2026-01-08',
    parties: [
      { role: 'buyer', name: 'Andrew & Maria Lopez', email: 'lopez@email.com' },
      { role: 'seller', name: 'Elizabeth Foster', email: 'efoster@email.com' },
    ],
    created_at: '2026-01-06T14:00:00Z',
    updated_at: '2026-01-19T09:20:00Z',
    buyer_name: 'Andrew & Maria Lopez',
    seller_name: 'Elizabeth Foster',
  },
  {
    id: 'tx-5',
    status: 'closed',
    transaction_type: 'purchase',
    property_address: {
      street: '7890 SW 8th Street',
      city: 'Miami',
      state: 'FL',
      zip_code: '33144',
    },
    purchase_price: 425000,
    closing_date: '2026-01-10',
    effective_date: '2025-12-01',
    parties: [
      { role: 'buyer', name: 'Carlos Rivera', email: 'crivera@email.com' },
      { role: 'seller', name: 'Nancy Wilson', email: 'nwilson@email.com' },
    ],
    created_at: '2025-11-28T10:00:00Z',
    updated_at: '2026-01-10T15:30:00Z',
    buyer_name: 'Carlos Rivera',
    seller_name: 'Nancy Wilson',
  },
];

export const mockUpcomingDeadlines: UpcomingDeadline[] = [
  {
    id: 'dl-1',
    name: 'Inspection Period Ends',
    title: 'Inspection Period Ends',
    due_date: '2026-01-22',
    days_remaining: 3,
    status: 'due_soon',
    deadline_type: 'inspection',
    transaction_id: 'tx-1',
    property_address: mockTransactions[0].property_address,
    is_statutory: false,
  },
  {
    id: 'dl-2',
    name: 'Loan Approval Deadline',
    title: 'Loan Approval Deadline',
    due_date: '2026-01-24',
    days_remaining: 5,
    status: 'upcoming',
    deadline_type: 'financing',
    transaction_id: 'tx-2',
    property_address: mockTransactions[1].property_address,
    is_statutory: false,
  },
  {
    id: 'dl-3',
    name: 'Title Commitment Review',
    title: 'Title Commitment Review',
    due_date: '2026-01-25',
    days_remaining: 6,
    status: 'upcoming',
    deadline_type: 'title',
    transaction_id: 'tx-1',
    property_address: mockTransactions[0].property_address,
    is_statutory: true,
  },
  {
    id: 'dl-4',
    name: 'Appraisal Deadline',
    title: 'Appraisal Deadline',
    due_date: '2026-01-20',
    days_remaining: 1,
    status: 'due_soon',
    deadline_type: 'appraisal',
    transaction_id: 'tx-3',
    property_address: mockTransactions[2].property_address,
    is_statutory: false,
  },
  {
    id: 'dl-5',
    name: 'HOA Document Review',
    title: 'HOA Document Review',
    due_date: '2026-01-28',
    days_remaining: 9,
    status: 'upcoming',
    deadline_type: 'hoa',
    transaction_id: 'tx-4',
    property_address: mockTransactions[3].property_address,
    is_statutory: true,
  },
];

export const mockDocumentsNeedingReview: Document[] = [
  {
    id: 'doc-1',
    transaction_id: 'tx-1',
    document_type: 'purchase_contract',
    filename: 'Purchase_Contract_1425_Ocean.pdf',
    content_type: 'application/pdf',
    status: 'needs_review',
    extraction_status: 'completed',
    extraction_confidence: 0.78,
    needs_review: true,
    needs_review_reason: 'Low confidence on closing date extraction',
    uploaded_at: '2026-01-15T10:00:00Z',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'doc-2',
    transaction_id: 'tx-2',
    document_type: 'seller_disclosure',
    filename: 'Seller_Disclosure_892_Brickell.pdf',
    content_type: 'application/pdf',
    status: 'needs_review',
    extraction_status: 'completed',
    extraction_confidence: 0.65,
    needs_review: true,
    needs_review_reason: 'Multiple unclear fields detected',
    uploaded_at: '2026-01-16T14:30:00Z',
    created_at: '2026-01-16T14:30:00Z',
  },
  {
    id: 'doc-3',
    transaction_id: 'tx-3',
    document_type: 'amendment',
    filename: 'Amendment_1_3200_Collins.pdf',
    content_type: 'application/pdf',
    status: 'needs_review',
    extraction_status: 'completed',
    extraction_confidence: 0.82,
    needs_review: true,
    needs_review_reason: 'Price change detected - verify accuracy',
    uploaded_at: '2026-01-18T09:15:00Z',
    created_at: '2026-01-18T09:15:00Z',
  },
];
